/**
 * Pure state transitions on the cached todo array. Optimistic updates use the
 * same rules the server enforces (ARCHITECTURE §7), so the UI is right before
 * the response arrives; the response then replaces the touched rows.
 */
import { byPosition, placeAmong } from "../../core/ordering";
import type { Placement, Todo } from "./types";

/** Live siblings in a container, sorted, optionally excluding one todo. */
export function siblingsOf(todos: readonly Todo[], p: Placement, excludeId?: string): Todo[] {
  return todos
    .filter(
      (t) =>
        t.id !== excludeId &&
        t.list_id === p.list_id &&
        t.section_id === p.section_id &&
        t.parent_id === p.parent_id,
    )
    .sort(byPosition);
}

/** Variables for creating a todo (the id is generated by the caller). */
export interface CreateTodoVars extends Placement {
  id: string;
  title: string;
  notes?: string;
  priority?: number;
  due_date?: string | null;
  tag_ids?: string[];
  before_id?: string | null;
  after_id?: string | null;
}

/** Builds the optimistic row for a create. */
export function buildTodo(todos: readonly Todo[], vars: CreateTodoVars, now: string): Todo {
  const placement = {
    list_id: vars.list_id,
    section_id: vars.section_id,
    parent_id: vars.parent_id,
  };
  return {
    id: vars.id,
    ...placement,
    title: vars.title.replace(/\s+/g, " ").trim(),
    notes: vars.notes ?? "",
    priority: vars.priority ?? 0,
    due_date: vars.due_date ?? null,
    position: placeAmong(
      siblingsOf(todos, placement),
      vars.before_id ?? null,
      vars.after_id ?? null,
    ),
    completed_at: null,
    created_at: now,
    updated_at: now,
    tag_ids: vars.tag_ids ?? [],
  };
}

/** Fields a patch may change. */
export type TodoPatch = Partial<
  Pick<Todo, "title" | "notes" | "priority" | "due_date" | "tag_ids">
>;

/** Applies a field patch to one todo. */
export function applyPatch(
  todos: readonly Todo[],
  id: string,
  patch: TodoPatch,
  now: string,
): Todo[] {
  return todos.map((t) => (t.id === id ? { ...t, ...patch, updated_at: now } : t));
}

/** Completes a todo and its open subtasks with one shared timestamp. */
export function applyComplete(todos: readonly Todo[], id: string, now: string): Todo[] {
  const target = todos.find((t) => t.id === id);
  if (target?.completed_at !== null) return [...todos];
  return todos.map((t) =>
    t.id === id || (t.parent_id === id && t.completed_at === null)
      ? { ...t, completed_at: now, updated_at: now }
      : t,
  );
}

/** Reopens a todo: a parent with what was completed with it, a subtask with its parent. */
export function applyReopen(todos: readonly Todo[], id: string, now: string): Todo[] {
  const target = todos.find((t) => t.id === id);
  if (target?.completed_at == null) return [...todos];
  const reopen = new Set([id]);
  if (target.parent_id === null) {
    for (const t of todos) {
      if (t.parent_id === id && t.completed_at === target.completed_at) reopen.add(t.id);
    }
  } else {
    const parent = todos.find((t) => t.id === target.parent_id);
    if (parent && parent.completed_at !== null) reopen.add(parent.id);
  }
  return todos.map((t) => (reopen.has(t.id) ? { ...t, completed_at: null, updated_at: now } : t));
}

/** Moves a todo (and its subtasks' container) next to the given neighbours. */
export function applyMove(
  todos: readonly Todo[],
  id: string,
  target: Placement,
  beforeId: string | null,
  afterId: string | null,
  now: string,
): Todo[] {
  const position = placeAmong(siblingsOf(todos, target, id), beforeId, afterId);
  return todos.map((t) => {
    if (t.id === id) return { ...t, ...target, position, updated_at: now };
    if (t.parent_id === id) {
      return { ...t, list_id: target.list_id, section_id: target.section_id, updated_at: now };
    }
    return t;
  });
}

/** Removes a todo and its subtasks. */
export function applyDelete(todos: readonly Todo[], id: string): Todo[] {
  return todos.filter((t) => t.id !== id && t.parent_id !== id);
}

/** Replaces rows by id with the server's versions (adding unknown ones). */
export function mergeTodos(todos: readonly Todo[], changed: readonly Todo[]): Todo[] {
  const byId = new Map(changed.map((t) => [t.id, t]));
  const merged = todos.map((t) => byId.get(t.id) ?? t);
  const known = new Set(todos.map((t) => t.id));
  return [...merged, ...changed.filter((t) => !known.has(t.id))];
}
