r"""Pins every runtime package (including transitive ones) in requirements.lock.txt.

Usage:
    py scripts\lock.py           regenerate after changing [project].dependencies
    py scripts\lock.py --check   fail if the lock no longer matches pyproject.toml

The lock is resolved with the oldest supported Python (3.12) when the py
launcher has it, so every pin installs on every supported machine. Both
install modes and CI install from it, which keeps the home and work PCs on
identical package versions.
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

from _common import LOCK_FILE, ROOT

HEADER = (
    "# Generated by scripts/lock.py from [project].dependencies in pyproject.toml.\n"
    "# Do not edit by hand. Regenerate: py scripts\\lock.py\n"
)
OLDEST_SUPPORTED = "3.12"


def normalize(name: str) -> str:
    """PEP 503 normalised project name."""
    return re.sub(r"[-_.]+", "-", name).lower()


def declared_pins() -> dict[str, str]:
    """The ``name==version`` pins from pyproject.toml, by normalised name."""
    with (ROOT / "pyproject.toml").open("rb") as fh:
        project = tomllib.load(fh)["project"]
    pins: dict[str, str] = {}
    for requirement in project["dependencies"]:
        name, sep, version = str(requirement).partition("==")
        if not sep:
            sys.exit(f"pyproject.toml: {requirement!r} must be pinned with ==")
        pins[normalize(name.strip())] = version.strip()
    return pins


def locked_pins(text: str) -> dict[str, str]:
    """The pins of a lock file's text, by normalised name."""
    pins: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, _, version = line.partition("==")
        pins[normalize(name)] = version
    return pins


def resolver_python() -> list[str]:
    """Interpreter command used to resolve: Python 3.12 via py if present, else this one."""
    launcher = shutil.which("py")
    if launcher is not None:
        probe = subprocess.run([launcher, f"-{OLDEST_SUPPORTED}", "-c", ""], check=False)
        if probe.returncode == 0:
            return [launcher, f"-{OLDEST_SUPPORTED}"]
    print(f"Python {OLDEST_SUPPORTED} not found; resolving with {sys.version.split()[0]}.")
    return [sys.executable]


def generate() -> None:
    """Resolves the runtime dependencies in a clean venv and writes the lock."""
    pins = declared_pins()
    with tempfile.TemporaryDirectory(prefix="planbox-lock-") as tmp:
        venv_dir = Path(tmp) / "venv"
        subprocess.run([*resolver_python(), "-m", "venv", str(venv_dir)], check=True)
        python = venv_dir / ("Scripts/python.exe" if sys.platform == "win32" else "bin/python")
        requirements = [f"{name}=={version}" for name, version in pins.items()]
        subprocess.run(
            [
                str(python),
                "-m",
                "pip",
                "install",
                "--quiet",
                "--disable-pip-version-check",
                *requirements,
            ],
            check=True,
        )
        frozen = subprocess.run(
            [str(python), "-m", "pip", "freeze"], check=True, capture_output=True, text=True
        ).stdout
    lines = sorted((line.strip() for line in frozen.splitlines() if "==" in line), key=str.lower)
    LOCK_FILE.write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {LOCK_FILE.name} with {len(lines)} packages.")


def check() -> int:
    """Fails when a pyproject pin is missing from the lock or differs."""
    if not LOCK_FILE.is_file():
        print("requirements.lock.txt is missing. Run: py scripts\\lock.py")
        return 1
    locked = locked_pins(LOCK_FILE.read_text(encoding="utf-8"))
    stale = [
        f"{name}=={version} (lock has {locked.get(name, 'nothing')})"
        for name, version in declared_pins().items()
        if locked.get(name) != version
    ]
    if stale:
        print("requirements.lock.txt is out of date: " + "; ".join(stale))
        print("Run: py scripts\\lock.py")
        return 1
    print("requirements.lock.txt matches pyproject.toml.")
    return 0


def main() -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of regenerating")
    if parser.parse_args().check:
        return check()
    generate()
    return 0


if __name__ == "__main__":
    sys.exit(main())
