/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Reports liveness and the applied schema versions.
         */
        get: operations["core_get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meta
         * @description Returns the app version, mode, timezone and week start.
         */
        get: operations["core_get_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthOut
         * @description Liveness and schema state.
         *
         *     Attributes:
         *         status: ``ok`` when the database answers.
         *         version: Application version.
         *         schema_versions: Highest applied migration per owner (``core``, module ids).
         */
        HealthOut: {
            /** Schema Versions */
            schema_versions: {
                [key: string]: number;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * MetaOut
         * @description Facts the frontend needs to agree with the backend.
         *
         *     Attributes:
         *         version: Application version.
         *         mode: ``serve``, ``dev`` or ``test``.
         *         timezone: IANA zone that defines "today".
         *         week_starts_on: ISO weekday the week starts on (1 = Monday).
         */
        MetaOut: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "serve" | "dev" | "test";
            /** Timezone */
            timezone: string;
            /** Version */
            version: string;
            /** Week Starts On */
            week_starts_on: number;
        };
        /**
         * Problem
         * @description An RFC 9457 problem document.
         *
         *     Attributes:
         *         type: URI reference identifying the problem type (``about:blank`` here).
         *         title: Short, human-readable summary of the problem type.
         *         status: The HTTP status code.
         *         detail: Explanation specific to this occurrence.
         *         code: Stable machine-readable code, e.g. ``not_found``.
         *         errors: Field-level details for validation problems.
         */
        Problem: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Problem details */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    core_get_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description Problem details */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
